Tilt to damage
ProtonMC/Proton pull request #53
Opened 2020-11-03 15:40 UTC by kara-b

Please test before accepting.

2020-11-03 15:42 UTC, YTG1234 commented on src/main/java/io/github/protonmc/proton/mixin/LivingEntityMixin.java
> +    public void takeKnockback(float f, double d, double e, CallbackInfo ci) {
Very descriptive parameter names 👍

2020-11-03 15:44 UTC, YTG1234 commented on src/main/java/io/github/protonmc/proton/mixin/LivingEntityMixin.java
> +package io.github.protonmc.proton.mixin;
should be inside a `tweaks` sub-package or a `tweaks.tilt_to_damage`

2020-11-03 16:00 UTC, YTG1234 requested changes

2020-11-03 16:00 UTC, YTG1234 commented on src/main/java/io/github/protonmc/proton/mixin/LivingEntityMixin.java
> +package io.github.protonmc.proton.mixin;
should be inside a `tweaks` sub-package or a `tweaks.tilt_to_damage` sub-package

2020-11-03 16:00 UTC, YTG1234 commented on src/main/java/io/github/protonmc/proton/module/tweaks/TiltToDamage.java
> +        super(Proton.identifier("tilt_to_damage"));
Missing lang entries

2020-11-04 13:19 UTC, YTG1234 commented
functionality works, just fix my requested changes and I'll approve

2020-11-09 12:50 UTC, YTG1234 approved these changes
Yes

2020-11-13 09:33 UTC, hYdos approved these changes

2020-11-14 13:33 UTC, YTG1234 commented
I think this is ready to merge

2020-11-14 13:39 UTC, merged